### PR TITLE
Aurora landing page: updated "recent projects" to become "recent blog posts"

### PR DESCRIPTION
**Pull request by kara**
Small PR to feature more blog posts on the Aurora landing page

cc @addyosmani

### CODE REVIEW

**Comment by addyosmani** [comment]
LGTM

**Review by rachelandrew — APPROVED** [review]

**Comment by kara** [comment]
@rachelandrew Is this ready to merge? I don't think I have permission to do it on my own :)

**Comment by rachelandrew** [comment]
For some reason it is stuck. I'll merge it!

**Comment by kara** [comment]
Thank you!!

**Pull request merged**
