### PR TITLE
Removing false information from page

### PR DESCRIPTION
**Pull request by IanStanion-google**
Fixes [#SOME_ISSUE_NUMBER](https://github.com/GoogleChromeLabs/Extension-Docs/issues/85)

Changes proposed in this pull request:

-Verified that information is incorrect and removed false statement.

### CODE REVIEW

**Comment by IanStanion-google** [comment]
@AmySteam I wasn't getting the stated confirmation dialog when requesting multiple permissions and also using override settings. I can maintain the information that this is against the single purpose policy, should I leave off the mention of that dialog box, or are you able to see that when you test?

**Comment by AmySteam** [comment]
Just to double check, were you [loading the extension locally](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked) or by [packing the extension](https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#view_warnings)?

**Comment by IanStanion-google** [comment]
My mistake... I was loading the extension locally and wasn't aware that only packed extensions received warnings. Sorry for the confusion!

**Comment by jpmedley** [comment]
Does @AmySteam's question have any bearing on whether this paragraph can be removed?

**Comment by AmySteam** [comment]
@IanStanion-google I would try packing the extension and testing it. If it doesn't work, I would follow-up with @dasli to confirm the behavior.

**Review by AmySteam — CHANGES_REQUESTED** [review]
Please check with David before removing.

**Comment by IanStanion-google** [comment]
The information removed in this PR was verified to still be correct.

**Pull request closed without merging**
