### PR TITLE
[JA] translations privacy-sandbox

### PR DESCRIPTION
**Pull request by ilyaspiridonov**
Japanese translations for:
docs/privacy-sandbox/first-party-sets/
docs/privacy-sandbox/fenced-frame/
docs/privacy-sandbox/permissions-policy/
docs/privacy-sandbox/shared-storage/
docs/privacy-sandbox/privacy-budget/

Translated by Alconost

### CODE REVIEW

**Comment by agektmr** [comment]
@ilyaspiridonov There is not changes to the First-Party Sets document?

**Comment by ilyaspiridonov** [comment]
> @ilyaspiridonov There is no changes to the First-Party Sets document? I noticed there is an old translation and required updates seem to be very subtle though. Have you ran translation process? If not, we may not need one.

Sorry, turns out it wasn't ready yet, I've just added it. 
The changes in the English version were subtle indeed, but we still ran the translation from scratch, so on the translated version the changes may look more substantial.

**Review by agektmr — CHANGES_REQUESTED** [review]
Need some changes.

**Review by agektmr — APPROVED** [review]
LGTM

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
