### PR TITLE
Update shared element transition article for origin trial

### PR DESCRIPTION
**Pull request by jakearchibald**
This is a significant change, so I'll also get engineers to review.

Preview: https://deploy-preview-3339--developer-chrome-com.netlify.app/blog/shared-element-transitions-for-spas/

### CODE REVIEW

**Comment by jakearchibald** [comment]
Should this article live somewhere else?

Is there a better style to use for the API reference?

**Comment by jakearchibald** [comment]
Pretty sure the use of 'please' in this article is acceptable.

**Comment by jh3y** [comment]
Looks great to me. Some great in-depth stuff there 👏

**Comment by rachelandrew** [comment]
@jakearchibald sorry for slow replies, are there any docs for this anywhere else? If not it would be great to have stuff in docs though get you might not have time right now. I have been going through the stuff to move from web.dev, but I probably need to trawl through this site as well and see what would be better as part of the web platform docs section.

**Comment by jakearchibald** [comment]
This does feel like more of a doc than a blog to me. Would it make sense to just move it and redirect, or does the style of the article need to change?

**Comment by jakearchibald** [comment]
Sorry, to answer your question, nah, this isn't documented elsewhere.

**Comment by rachelandrew** [comment]
Ultimately I'd like them to be in more of a documentation format, as my hope is that eventually we'd move the canonical docs to MDN (once the thing is in stable and MDN want them). So we'd have blog posts doing genuine updates, which we'd leave as the paper trail and history but our docs really be seen as a staging area for MDN docs.

That said, right now I'll put anything in any format there :D however it might be worth then doing a quick blog post announcing the changes and pointing to the docs as that will show up in people's feed readers at the top (which updates to old posts don't).

**Comment by jakearchibald** [comment]
In MDN terms, I think this is more in the "Using shared element transitions" format, than the API reference docs.

**Comment by rachelandrew** [comment]
@jakearchibald let's publish this where it is and then figure it out, I think there are probably a bunch of things that could do with some actual docs being created (by pulling out the relevant bits from articles and blog posts). Once I've moved the ones off web.dev I'll start going through and making a list.

**Review by rachelandrew — APPROVED** [review]

**Comment by jakearchibald** [comment]
Thank you! I'm still planning to write a little 'cookbook' of transitions, but I'll chat to you about where that should live when I'm ready to write it.

**Pull request merged**
