### PR TITLE
Update tags for deprecations and removals.

### PR DESCRIPTION
**Pull request by jpmedley**
After years of using them, I've found little difference in content between items tagged deprecation and items tagged removal. This PR combines them into a single tag.

### CODE REVIEW

**Comment by jpmedley** [comment]
I don't see much value in editing old documents for new standards.

**Comment by rachelandrew** [comment]
@jpmedley the linter is objecting as you need to add the tag in the i18n file.

**Comment by jpmedley** [comment]
I pushed a change

**Review by rachelandrew — APPROVED** [review]

**Comment by jpmedley** [comment]
It looks like I can't merge this without a review from someone in @devnook 's group.

**Pull request merged**
