### PR TITLE
[WasmGC article] Change Kotlin's warning based on @mit-mit's feedback

### PR DESCRIPTION
**Pull request by tomayac**
Changes proposed in this pull request:

- Change Kotlin's warning based on @mit-mit's feedback.

### CODE REVIEW

**Review by mit-mit — COMMENTED** [review]
Kotlin change LGTM

I suggest we update the Dart message too in a similar way:

```
Dart WasmGC compilation and Flutter Web with WasmGC are in preview, and are to be used only for evaluation purposes.

The [Flutter Web WasmGC Preview demo](https://flutterweb-wasm.web.app/) currently uses Flutter's [CanvasKit renderer](https://docs.flutter.dev/platform-integration/web/renderers) which fully renders onto a `canvas`. This means it breaks important browser features like find on page, translation, text selection, extensions, and link to text fragment.
```

**Comment by mit-mit** [comment]
> Change Kotlin's warning based on @mit-mit's feedback.

Thanks Thomas! My goals here are 1) to align the messaging across Kotlin and Dart/Flutter, and 2) to separate the comments about the current experiment stage from the comments about the implications of rendering to `Canvas`.

**Comment by tomayac** [comment]
@mit-mit PTAL at both warnings again! Thanks for the feedback.

**Review by mit-mit — COMMENTED** [review]
LGTM!

**Comment by tomayac** [comment]
Over to @rachelandrew. I probably have to refile this for DevSite, but started it here for easily getting Michael's review.

**Comment by rachelandrew** [comment]
I'll review it in a CL on DevSite or I'm doing the work twice, perhaps get comments in a doc until we're moved over? As it's going to get confusing.

**Comment by tomayac** [comment]
Alright, so this will need to be in a CL once the migration to DevSite has happened I was told by @rachelandrew. Until then, we're in a content freeze. I ping you the link to the timeline for the migration over internal chat, @mit-mit. Thanks!

**Comment by tomayac** [comment]
Migrated to cl/584259559.

**Pull request closed without merging**
