### PR TITLE
Consolidate action material

### PR DESCRIPTION
**Pull request by jpmedley**
If the action material is on the same page is should be in the same place.

This will make sense if you compare the staged rendering to the current version of the page.

### CODE REVIEW

**Comment by AmySteam** [comment]
If you are moving all Action APIs into the same section, would the popup and tooltip also go under [The extension action](https://pr-7398-static-dot-dcc-staging.uc.r.appspot.com/docs/extensions/mv3/user_interface/#action)?

**Review by AmySteam — CHANGES_REQUESTED** [review]
Can we explore moving the other action API items into the same section? Other than that it LGTM 👍

**Comment by jpmedley** [comment]
> Can we explore moving the other action API items into the same section?

Do you mean this: https://pr-7398-static-dot-dcc-staging.uc.r.appspot.com/docs/extensions/mv3/user_interface/#icons

Yeah, I failed to notice that one. I can move it now.

**Comment by jpmedley** [comment]
@AmySteam Would you mind looking at [my latest change](https://github.com/GoogleChrome/developer.chrome.com/pull/7398/commits/6d5ef77cbe14abe76d36724c7ba8524bff9e0550). Make sure I didn't introduce any new problems.

**Comment by AmySteam** [comment]
> > Can we explore moving the other action API items into the same section?
> 
> Do you mean this: https://pr-7398-static-dot-dcc-staging.uc.r.appspot.com/docs/extensions/mv3/user_interface/#icons
> 
> Yeah, I failed to notice that one. I can move it now.

I meant the tooltip https://pr-7398-static-dot-dcc-staging.uc.r.appspot.com/docs/extensions/mv3/user_interface/#tooltip and the popup, since they are both part of the Action API. 

Sorry I should have been mre explicit

**Comment by jpmedley** [comment]
I moved the popup section too. You should probably look at this again.

**Comment by jpmedley** [comment]
These are good catches. I don't know why I didn't think of them.

**Review by AmySteam — APPROVED** [review]
LGTM 👍

**Pull request merged**
