### PR TITLE
[devtools-translate] Portuguese - What's New in DevTools (Chrome 107) #3754

### LINKED ISSUE #3754: [devtools-translate] Portuguese - What's New in DevTools (Chrome 107)
Post: https://developer.chrome.com/blog/new-in-devtools-107/
Translated by: Oct-11

Translator: @alvarocamillont
Reviewers: @khaosdoctor,

### PR DESCRIPTION
**Pull request by alvarocamillont**
Fixes #3754

Changes proposed in this pull request:

Add portuguese translations for What's New in DevTools M107

### CODE REVIEW

**Comment by alvarocamillont** [comment]
@khaosdoctor  Can You review it?

Thanks!

**Review by thiagowfx — APPROVED** [review]

**Comment by jecfish** [comment]
Thanks Thiago for the review. Good to go!

**Comment by khaosdoctor** [comment]
Sorry I'm abroad and couldn't review it timely :/

**Comment by jecfish** [comment]
Hey hey, no worries at all. You should enjoy your vocation! Next WNDT is waiting for you, haha.

**Pull request merged**
