### PR TITLE
fix(doc): update codeceptjs chrome recorder ext

### PR DESCRIPTION
**Pull request by PeterNgTr**
- update codeceptjs chrome recorder ext

### CODE REVIEW

**Review by sofiayem — APPROVED** [review]

**Comment by sofiayem** [comment]
@PeterNgTr Thank you for your contribution. Please sign the Google CLA by following [these instructions](https://github.com/GoogleChrome/developer.chrome.com/pull/5126/checks?check_run_id=11064932231)

**Comment by PeterNgTr** [comment]
Hey @sofiayem may you have chance for this PR 😄

**Comment by jecfish** [comment]
Thanks & merged! You should see the changes live in ~an hour.

**Comment by PeterNgTr** [comment]
Thank you @jecfish

**Pull request merged**
