### PR TITLE
[JA] Privacy Sandbox Nov translations

### PR DESCRIPTION
**Pull request by ilyaspiridonov**
MTPE by Alconost

### CODE REVIEW

**Comment by ilyaspiridonov** [comment]
CC: @agektmr

**Comment by agektmr** [comment]
I see rendering issues on `/docs/privacy-sandbox/protected-audience` and `/docs/privacy-sandbox/protected-audience-api/ad-auction`. Everything else looks fine.

Screenshot 2023-11-17 at 19 46 45
Screenshot 2023-11-17 at 19 46 29

**Comment by agektmr** [comment]
@ilyaspiridonov Could you please identify the issue and fix?

**Comment by ilyaspiridonov** [comment]
@agektmr can you please check again? The issue was in the {% Aside %} tags inside numbered lists

**Comment by agektmr** [comment]
@ilyaspiridonov the problem has been fixed. Thank you for your quick turnaround!

**Review by agektmr — APPROVED** [review]
LGTM

**Review by anusmitaray — APPROVED** [review]

**Pull request merged**
