### PR TITLE
Correction to article name

### PR DESCRIPTION
**Pull request by samdutton**
https://deploy-preview-2056--developer-chrome-com.netlify.app/docs/privacy-sandbox/fledge/

### CODE REVIEW

**Comment by heyawhite** [comment]
What would you think about updating the article title as well to just "FLEDGE"? Or could be "FLEDGE API"?

Same question goes for the Topics API as well.

**Comment by samdutton** [comment]
@heyawhite SG. (You mean instead of 'The ...'?)

**Comment by heyawhite** [comment]
@samdutton exactly!

**Review by heyawhite — APPROVED** [review]
LGTM, with open question re: article title updates

**Pull request merged**
