### PR TITLE
Screen sharing improvements in Chrome 109: triple equal

### PR DESCRIPTION
**Pull request by tomayac**
CC: @beaufortfrancois 

Changes proposed in this pull request:

- Triple equals

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
As `displaySurface` is a string [according to WebIDL](https://w3c.github.io/mediacapture-screen-share/#ref-for-dom-displaycapturesurfacetype-4), what is the benefit of using `===` there?

**Comment by tomayac** [comment]
Just good code style.

**Comment by tomayac** [comment]
As in style guide adherence.

**Comment by beaufortfrancois** [comment]
Got it. Feel free to merge if you can!

**Comment by tomayac** [comment]
I can’t, but over to @rachelandrew.

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
