### PR TITLE
 [devtools-translate] Portuguese - What's New in DevTools (Chrome 101) #2581

### PR DESCRIPTION
**Pull request by alvarocamillont**
Fixes https://github.com/GoogleChrome/developer.chrome.com/issues/2581

Changes proposed in this pull request:

Add portuguese translations for What's New in DevTools M101

### CODE REVIEW

**Comment by jecfish** [comment]
Over to @khaosdoctor @andreban for review!

**Review by andreban — APPROVED** [review]
LGTM, great stuff!

**Review by khaosdoctor — COMMENTED** [review]
LGTM

**Comment by jecfish** [comment]
Thank you all!

**Pull request merged**
