### PR TITLE
[Anonymous iframes article] Call out `require-corp` is not a typo

### PR DESCRIPTION
**Pull request by tomayac**
Changes proposed in this pull request:

- `s/require-corp/require-coep`

### CODE REVIEW

**Comment by agektmr** [comment]
This is not a typo. COEP does require CORP for 3p resources to opt-in.

**Comment by agektmr** [comment]
It does require COEP as well for iframes though.

**Comment by tomayac** [comment]
Wow, then this probably should be called out somehow. The article talks about `COEP`, and on the English keyboard `e` and `r` are next to each other, so it looked like a typo. 

PTAL for the new aside that calls this out.

**Review by agektmr — APPROVED** [review]
LGTM

**Pull request merged**
