### PR TITLE
[devtools-translate] Portuguese - What's New in DevTools (Chrome 100) #2268

### LINKED ISSUE #2268: [devtools-translate] Portuguese - What's New in DevTools (Chrome 100)
Post: https://developer.chrome.com/blog/new-in-devtools-100/

Translator: @alvarocamillont 
Reviewers: @khaosdoctor

Translated by: Mar 22

### PR DESCRIPTION
**Pull request by alvarocamillont**
Fixes #2268

Changes proposed in this pull request:

Add portuguese translations for What's New in DevTools M100

### CODE REVIEW

**Comment by khaosdoctor** [comment]
For some reason I can't approve it but LGTM

**Comment by jecfish** [comment]
Thanks Lucas. Over to @andreban for final review.

**Review by andreban — APPROVED** [review]
LGTM, thank you!

**Review by jecfish — APPROVED** [review]

**Comment by jecfish** [comment]
Thank you all!

**Pull request merged**
