### PR TITLE
Fix typo `rotect` -> `protect`

### PR DESCRIPTION
**Pull request by fwitzke**

### CODE REVIEW

**Comment by jpmedley** [comment]
@fwitzke Thank you for submitting this. Can you please sign the CLA.

**Comment by fwitzke** [comment]
@googlebot I signed it!

**Comment by jpmedley** [comment]
@fwitzke Thank you for signing the CLA. By any chance do you have multiple email addresses associated with your GitHub account. When you signed the CLA, our bot should have attached a label to your PR. (We've had trouble with this before.)

**Comment by fwitzke** [comment]
> @fwitzke Thank you for signing the CLA. By any chance do you have multiple email addresses associated with your GitHub account. When you signed the CLA, our bot should have attached a label to your PR. (We've had trouble with this before.)

I do have multiple emails associated with my GitHub account, and I can confirm the one used for signing the CLA is associated with my account (not sure if this information helps). Also, if it's too complicated to get this PR mergeable, feel free to just update the docs directly, it's such a tiny change anyway.

**Review by samthor — APPROVED** [review]

**Pull request merged**
