### PR TITLE
Fix links in ARA dev guide landing

### PR DESCRIPTION
**Pull request by nancymic2**
Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- Fix links to register sources and register triggers. (no ending 's')
- https://pr-7748-static-dot-dcc-staging.uc.r.appspot.com/docs/privacy-sandbox/attribution-reporting/developer-guide/
-

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]

**Review by nancymic2 — COMMENTED** [review]
not merging

**Comment by rachelandrew** [comment]
After tomorrow they won't be able to be merged due to the content freeze. You'll need to make the change on the migrated content.

**Comment by nancymic2** [comment]
I must have created this with my personal email again somehow

**Comment by rachelandrew** [comment]
Oh I see, I thought "not merging" meant you weren't going to merge it, not that you couldn't. Shall I merge it?

**Pull request merged**
