### PR TITLE
Update framework INP values (Feb 2023)

### PR DESCRIPTION
**Pull request by rviscomi**
Updates the CrUX INP data for frameworks in https://developer.chrome.com/blog/inp-in-frameworks/#experimental-responsiveness-metric-data and converts to article format (rather than blog)

Preview: https://deploy-preview-5867--developer-chrome-com.netlify.app/articles/inp-in-frameworks

### CODE REVIEW

**Review by addyosmani — APPROVED** [review]

**Comment by rachelandrew** [comment]
This seems to be a [blog post](https://developer.chrome.com/docs/handbook/where-to-publish/#blog-posts), making it very strange to update to 2023 values. I'd suggest writing a new blog post for these values or, if you want this to be evergreen content, moving it to `/articles`.

**Comment by rviscomi** [comment]
@kara WDYT? Is there enough new substance (besides the updated stats) for another blog post, or is this something you see us updating regularly in an article format?

**Comment by kara** [comment]
SGTM!

**Comment by rviscomi** [comment]
Moved from blog to article and set up a redirect, although it still seems to be 404ing in the [preview](https://deploy-preview-5867--developer-chrome-com.netlify.app/blog/inp-in-frameworks/). The config looks ok to me so maybe this is WAI. @rachelandrew can you take another look?

**Comment by rachelandrew** [comment]
@rviscomi I don't think redirects work in the preview. I spotted in the conclusion this post says "We will take steps to provide more actionable guidance on the metric in 2022-23. " which seems outdated, we now have stuff on web.dev on INP so perhaps point there?

**Comment by rviscomi** [comment]
@addyosmani @kara could you suggest an updated conclusion?

**Comment by kara** [comment]
> @addyosmani @kara could you suggest an updated conclusion?

Perhaps we can link to the INP docs as @rachelandrew suggests, but change the wording, e.g.:
```
- We will build on our [existing INP guide](link) to provide more actionable tips for framework developers in 2023.
```

**Comment by rviscomi** [comment]
Back from leave and looking at this again. @kara should I still go forward with your suggestion? I can update with the latest data while I'm in there too.

**Comment by kara** [comment]
@rviscomi That works for me!

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
