### PR TITLE
[devtools-translate] Russian - What's New in DevTools (Chrome 103) 

### LINKED ISSUE #3017: [devtools-translate] Russian - What's New in DevTools (Chrome 103)
Post: https://developer.chrome.com/blog/new-in-devtools-103/
Translated by: June 19

Translator: @solarrust
Reviewers: @webmaxru, @kateryna-prokopenko

### PR DESCRIPTION
**Pull request by solarrust**
Fixes #3017

Hi @jecfish, @kateryna-prokopenko and @webmaxru ! 🙌

Please, help me with the last paragraph. I am awful in it 🥲
Lines 217-219. Thank you! 🫶

### CODE REVIEW

**Comment by jecfish** [comment]
Thanks Alena, over to @kateryna-prokopenko and @webmaxru for review!

**Comment by jecfish** [comment]
Oh, Kateryna, is OOO, so @webmaxru will be the only reviewer this time.

**Comment by webmaxru** [comment]
Hello! Happy to help! But for some reason the "suggest" feature is disabled for me - I can only comment on the lines, not suggest changes. I believe, having suggestions will speed up the whole flow. Should I be explicitly nominated as a reviewer for it?

**Comment by jecfish** [comment]
Interesting @webmaxru, didn't know the suggest feature is missing for non-repo member, that's not good. I can't nominate you as a reviewer because you are not part of the repo member.

I will try to find out how to enable that (or grant you rights), but I think I might not get the solution so soon. In the meantime, please do regular comments.

**Comment by webmaxru** [comment]
@jecfish FYI: it worked fine for the previous versions, so I assume something was changed in permissions model recently

**Comment by jecfish** [comment]
Not yet found the solution. Can you try to manually force the suggest and see what happen? Use enclose your suggestion with triple ` and suggest.

\`\`\`suggest
Your proposed changes
\`\`\`

**Comment by webmaxru** [comment]
@jecfish I believe, this "Suggest" button appeared after my first comment :) Will check how that exactly works in 104's issue :)

**Comment by jecfish** [comment]
Thanks Maxim. Back to you @solarrust!

**Review by jecfish — APPROVED** [review]

**Comment by jecfish** [comment]
Thanks both!

**Pull request merged**
