### PR TITLE
Popover API attribute name changes

### LINKED ISSUE #5562: Update popover attribute content
`popovertoggletarget/popoverhidetarget/popovershowtarget="ID"` have been changed to `popovertarget="ID" popovertargetaction="toggle|hide|show"`

This needs to be updated on blog posts and different documentation pages:

- https://developer.chrome.com/docs/web-platform/popover-api/popover-attribute/
- and all the links in the See Also section: https://developer.chrome.com/docs/web-platform/popover-api/popover-attribute/#see-also

Demos on the blog posts also need updating.

### PR DESCRIPTION
**Pull request by AaronForinton**
Fixes #5562

### CODE REVIEW

**Comment by AaronForinton** [comment]
@jh3y I wonder if you could also give this a look, or find someone else who has written on this API who might be able to confirm these changes (I'm sure a few tweaks are needed).

**Review by jh3y — COMMENTED** [review]
Hey @AaronForinton 👋 

Think the docs are right 🤔 Erm. I can't remember what the POA was for the article. I thought there was going to be a new article written for the API. This was because the API has shifted a few times already and there are a lot of demos to update, etc.

**Comment by rachelandrew** [comment]
@AaronForinton can we remove the blog post from this PR (instead we could [add the outdated banner to it](https://developer.chrome.com/docs/handbook/where-to-publish/#blog-posts)) as we'll write a new post when it lands rather than rewrite history. The blog on d.c.c. is actually a blog/news.

**Comment by AaronForinton** [comment]
@rachelandrew I've removed the blog.

**Review by rachelandrew — APPROVED** [review]

**Comment by AaronForinton** [comment]
@nt1m Could I ask you to follow the instructions [here](https://github.com/GoogleChrome/developer.chrome.com/pull/5699/checks?check_run_id=12074240468) so your commit is covered by our CLA? Otherwise I can't merge the changes.

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
