### PR TITLE
Fixes typo in Custom Tabs Integration

### LINKED ISSUE #648: val name is incorrect
⚠️ This is for issues with the https://developer.chrome.com/docs/android/custom-tabs/integration-guide/ site, not Chromium itself.

**Describe the bug**
*incorrect val name*
int coolorInt = Color.parseColor("#FF0000"); //red
builder.setToolbarColor(colorInt);

**Expected behavior**
int colorInt = Color.parseColor("#FF0000"); //red
builder.setToolbarColor(colorInt);

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.128

### PR DESCRIPTION
**Pull request by andreban**
Closes #648

### CODE REVIEW

**Review by jpmedley — APPROVED** [review]

**Comment by robdodson** [comment]
@andreban it looks like this can land but there's a linter error:

```
site/en/blog/new-in-extensions-2/index.md
  23:1-26:67  warning  No smart quotes or apostrophes. Use a straight quote or apostrophe instead.  no-smart-quotes  remark-lint
```

We usually disallow smart quotes because they sometimes sneak into code samples. If you want to resolve this you can either replace the smart quote, or add `<!--lint disable no-duplicate-headings-->` to your file.

**Comment by andreban** [comment]
Hey Rob, the lint error is unrelated to this change. The issue is on `site/en/blog/new-in-extensions-2/index.md`, but this change  only touches `site/en/docs/android/custom-tabs/integration-guide/index.md`. I was going to submit a change fixing that anyway, but it's already fixed on the `main` branch (resulting in a conflict).

**Comment by andreban** [comment]
@robdodson @jpmedley Unless there's another change required here, can you merge. I don't have access to merge the PR.

**Comment by robdodson** [comment]
done, thank you!

**Pull request merged**
