### PR TITLE
[POST] GridNG Crosspost

### PR DESCRIPTION
**Pull request by una**

### CODE REVIEW

**Comment by rachelandrew** [comment]
@una is this the same post that has an issue raised for it on web.dev? https://github.com/GoogleChrome/web.dev/issues/5963

**Comment by una** [comment]
> @una is this the same post that has an issue raised for it on web.dev? [GoogleChrome/web.dev#5963](https://github.com/GoogleChrome/web.dev/issues/5963)

Yes

**Comment by samthor** [comment]
Assigning back to @una. We have an internal thread about whether reposting verbatim is a good idea.

**Comment by jeffposnick** [comment]
Can we close this PR, @una, given that https://blogs.windows.com/msedgedev/2021/08/10/compat2021-css-grid-gridng/ has the same content?

**Pull request closed without merging**
