### PR TITLE
Events  - Content updates

### PR DESCRIPTION
**Pull request by johnrich85**
Adds some new events and updates others.

### CODE REVIEW

**Review by rachelandrew — CHANGES_REQUESTED** [review]
Looking at the preview, there seems to be a duplicate event for the PerfNow pre-event, does this PR add a duplicate?

**Comment by devnook** [comment]
@rachelandrew PTAL

**Comment by johnrich85** [comment]
Ah yeah, good spot. That was supposed to be an update rather than an addition. I've deleted the duplicate and updated the original instead

**Comment by johnrich85** [comment]
Apologies @rachelandrew . That should be sorted now.

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
