### PR TITLE
updates types infra, add version data

### LINKED ISSUE #39: New site is missing API version information
I found there is no "Since Chrome _version_" in new api reference. In the past, there are many statement say like "Since Chrome 48". This information is useful for compatibility. Developers can detect features or set "minimum_chrome_version" in manifest.

### LINKED ISSUE #360: Many new apis listing as Stable APIs. Is it a bug?
Sorry, I don't use issue template. I just want to confirm the situation first.

I find there are `app.runtime`, `app.window`,  `socket`, `sockets.tcp`, `sockets.tcpServer`, `sockets.udp` (maybe more) listing on the [API Reference](https://developer.chrome.com/docs/extensions/reference/) page. Is these a bug? I remember they are chrome app api, not extension api.

In addition, I find `processes` api listing as Stable APIs, but I remember it is Dev APIs in the past. Is this a bug?

### LINKED ISSUE #362: Chrome Extension API chrome.tabGroups is Stable but not accessible in Stable Channel
When attempting to load an extension into the Stable build of Chrome with the manifest permissions including "tabGroups", an error stating "'tabGroups' requires dev channel or newer, but this is the stable channel." occurs. However, the Chrome extension API lists "tabGroups" as stable [here](https://developer.chrome.com/docs/extensions/reference/). Shouldn't the tabGroups API be accessible in the stable build?

**To Reproduce**
1. Build a chrome extension as shown [here ](https://developer.chrome.com/docs/extensions/mv3/getstarted/)
2. In the manifest.json of a chrome extension, under "permissions" include ["tabGroups"].
3. At [chrome://extensions/](chrome://extensions/), click Load Unpacked and select the application just created. 
4. Click "Errors" under the newly loaded extension.
5. One of the reported errors should be a warning stating "'tabGroups' requires dev channel or newer, but this is the stable channel."

**Expected behavior**
Any calls to the chrome.tabGroups API should be valid according to https://developer.chrome.com/docs/extensions/reference/tabGroups/ because the API should be stable. Currently, any calls to the chrome.tabGroups API are undefined.

There should not be a warning that tabGroups requires the dev channel because according to the documentation, the tabGroups API should be included in the stable channel already.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 
 - Version 88.0.4324.146 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by samthor**
Fixes #362
Fixes #360
Fixes #39

### CODE REVIEW

**Comment by hanguokai** [comment]
I see the new "Availability", "Since Chrome" and  "Deprecated" field in the API reference. That's great. I really don't care about api version info before chrome 39.

But I find some problems, **for examples**:

- tabGroups api is listed in both Stable APIs and Dev APIs
- tabGroups api shows 'chrome 88', but it is not available in chrome 88.
- chrome.processes api is listed in Stable APIS and shows 'Since Chrome 51', but it is always dev version only.
- chrome.socket* api are listed in extension api, but they are chrome app api, not available in extension.

**Comment by samthor** [comment]
Thanks for the testing!

**Comment by samthor** [comment]
I've pushed an updated version which should fix the issues raised by @hanguokai. I'd also appreciate another look by @rdcronin and @karan173. Thanks!

**Comment by hanguokai** [comment]
I find another issue in API reference at https://deploy-preview-364--developer-chrome-com.netlify.app/docs/extensions/reference/ .
system.* including `system.cpu`, `system.memory`, `system.display`, `system.storage` apis no longer exist, new bug?

**Comment by benmeiri** [comment]
Any update on this one? Waiting for the `tabGroups` to be available in non dev environments.

**Pull request closed without merging**
