### PR TITLE
Add JSON to the list of web technologies

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by jpmedley** [comment]
@AmySteam, the link to MDN was already in the file.

**Review by AmySteam — COMMENTED** [review]
I think this list if getting too big already. My inclination would be no, but if any of the DRE's thinks it's valuable... sure...

@oliverdunk @sebastianbenz @patrickkettner  Thoughts?

**Comment by patrickkettner** [comment]
agree the llist is long. But I thnk JSON is less liekly to be known then CSS, so 🤷‍♀️

**Comment by jpmedley** [comment]
I added some context that I think will make this list less scary for potential extension developers.

I think it's important to give complete information to potential extension developers. This also saves us some reworking in another document.

**Comment by jpmedley** [comment]
Pinging on this again. Thoughts?

**Comment by oliverdunk** [comment]
> Pinging on this again. Thoughts?

To be honest, I'm not sure that this is particularly helpful (JSON is implied by JS for the most part, as is knowledge of web APIs). I think this change may actually make things more verbose but I'm not strongly opposed if we decide we really want it.

**Comment by AmySteam** [comment]
> > Pinging on this again. Thoughts?
> 
> To be honest, I'm not sure that this is particularly helpful (JSON is implied by JS for the most part, as is knowledge of web APIs). I think this change may actually make things more verbose but I'm not strongly opposed if we decide we really want it.

I liked the simplicity of the original approach: CSS, HTML, and JS.

**Comment by sebastianbenz** [comment]
+1 to the other's feedback, I think this update is well intended but not really helpful / actionable for readers.

**Comment by oliverdunk** [comment]
I still feel somewhat indifferent on this. I'm not against it, but I'm not sure it adds much. Will defer to others on if we make the  change :)

**Pull request closed without merging**
