### PR TITLE
Issue/184

### LINKED ISSUE #184: Finish MV3ization for page: Content scripts
The page [Content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/) page is not compliant with MV3. It needs to be checked and updated for manifest contents, API use, etc.

### PR DESCRIPTION
**Pull request by awfuchs**
Modifications to the content scripts page for MV3 launch. Technical updates by dotproto, editorial tweaks by awfuchs. There's a chunk of remaining TODO bracketed in an {% if false %} that we should still address.

Resolves #184

### CODE REVIEW

**Review by dotproto — APPROVED** [review]
Good enough shape for now, but we should definitely come back to this. We still need to…

* flesh out the intro of the "Inject with dynamic declarations" section to better match the style of the sibling sections
* flesh out the examples in the "Inject with dynamic declarations" section
* link to the appropriate Scripting API documentation when it exists
* link to an example extension to show off content script injection and usage patterns

**Comment by awfuchs** [comment]
Opened #281 to capture this work.

**Comment by robdodson** [comment]
@awfuchs please merge when you're ready

**Comment by awfuchs** [comment]
Ah yes, I forgot the "confirm merge" button...

**Pull request merged**
