### PR TITLE
Remove deprecated event_rules manifest key

### PR DESCRIPTION
**Pull request by IanStanion-google**
Fixes [#SOME_ISSUE_NUMBER](https://github.com/GoogleChromeLabs/Extension-Docs/issues/85)

Changes proposed in this pull request:

- Removes unsupported mv2 manifest key

### CODE REVIEW

**Review by AmySteam — APPROVED** [review]
LGTM 👍

**Comment by jpmedley** [comment]
The reference didn't get forked for MV3 the way our conceptual material did. Until we end support for Manifest V2, we probably shouldn't remove anything for MV2.

**Comment by jpmedley** [comment]
@IanStanion-google, I messed up. This is content that exists in the MV2 material. The point I made about reference content needing to stay only applies to the API reference. That's the one that's not duplicated. 

I'm reopening this. Can you please add a redirect to the [MV2 version](https://developer.chrome.com/docs/extensions/mv2/manifest/event_rules/) of this page.

**Comment by IanStanion-google** [comment]
@jpmedley Got it.
So should we add the redirect on the mv3 manifest file page, or take off the reference to this key there still? Just want to make sure I'm putting references to mv2 content in the appropriate spots

**Comment by jpmedley** [comment]
Remove the change to the manifest file page from your PR and let the redirect handle it. Add a note to the top of the MV2 page telling readers they were redirected from MV3 and that the feature is not supported in MV3. In a month I'll look at the analytics for the MV2 page and reconsider whether to remove from the manifest file page.

**Review by jpmedley — APPROVED** [review]

**Pull request merged**
