### PR TITLE
[JA] Translate Permissions Policy

### PR DESCRIPTION
**Pull request by ilyaspiridonov**
Updates Japanese translation for site/ja/docs/privacy-sandbox/permissions-policy/index.md
Post-Edited Machine Translation by Alconost.
[See review request on GitLocalize](https://gitlocalize.com/repo/7832/ja/review/56399)

### CODE REVIEW

**Comment by ilyaspiridonov** [comment]
CC: @agektmr

**Review by agektmr — APPROVED** [review]
LGTM

**Review by anusmitaray — APPROVED** [review]

**Comment by namsturp** [comment]
Hey web growing chains branches

**Pull request merged**
