### PR TITLE
Correct the path to creating a release

### PR DESCRIPTION
**Pull request by hhimanshu**
Changes proposed in this pull request:

- The documentation to create App Signing no longer matches the current UX workflow. This PR updates the steps

The demo is available 👇 

https://user-images.githubusercontent.com/6589036/126671450-b47ff909-d197-4c66-8ae0-d5f49d3d195f.mp4

### CODE REVIEW

**Comment by samthor** [comment]
This seems sane but actually my Play account won't let me get to those pages. Can you point at a screenshot that shows this off?

**Comment by hhimanshu** [comment]
@samthor , I updated the description above with the demo video. I hope that helps

**Comment by samthor** [comment]
Thanks, and I appreciate you blanking out your keys! 🤣

**Review by samthor — APPROVED** [review]

**Comment by samthor** [comment]
Thanks, and I appreciate you blanking out your keys! 🤣

**Comment by hhimanshu** [comment]
ha ha, fantastic! Thanks @samthor

**Pull request merged**
