### PR TITLE
wrap choices in parens when used in array

### LINKED ISSUE #1421: Type description for `ports` property of events.UrlFilter is confusing
**Describe the bug**

Type description for `ports` property of [events.UrlFilter](https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter) is confusing. The type signature for this property is listed as "number | number[][] optional". 

The description helps clarify what the property actually accepts with an example: "For example [80, 443, [1000, 1200]] matches all requests on port 80, 443 and in the range 1000-1200." I believe the correct Typescript style notation for what this property accepts is `(number | number[])[]`.

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter
3. Scroll down to the "ports" property.
4. Observe that the type signature provided for this property does not match what is shown in the example.

**Expected behavior**
The type signature should accurately reflect what Chrome accepts.

**Screenshots**
screenshot

**Additional context**
This issue was migrated from https://crbug.com/161501

### PR DESCRIPTION
**Pull request by samthor**
Fixes #1421

### CODE REVIEW

**Comment by dotproto** [comment]
The change looks good, but when I tried to test this locally I encountered a "failed to parse" error. The below output is trimmed for length.

```
failed to parse
{
  compiler_options: { generate_error_messages: true },
  description: ' The <code>chrome.declarativeNetRequest</code> API is used to block or modify\n' +
    ' network requests by specifying declarative rules. This lets extensions\n' +
    ' modify network requests without intercepting them and viewing their content,\n' +
    ' thus providing more privacy.',
  nodoc: false,
  platforms: null,
  manifest_keys: {
    declarative_net_request: { nodoc: true, name: 'declarative_net_request', '$ref': 'DNRInfo' }
  },
…
}
> got multiple ambig for api:declarativeNetRequest: 2

`Error` was thrown:
    Error: got multiple ambig for api:declarativeNetRequest: 2
        at Features.#singleResolve (/Users/simeonv/dev/dcc/node_modules/chrome-types-helpers/lib-gen-main.cjs:1079:13)
        at Features.query (/Users/simeonv/dev/dcc/node_modules/chrome-types-helpers/lib-gen-main.cjs:1119:41)
        at JSONSchemaParser.parse (/Users/simeonv/dev/dcc/node_modules/chrome-types-helpers/lib-gen-main.cjs:2171:47)
…
        at async TemplateData.getData (/Users/simeonv/dev/dcc/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
ERROR: "eleventy:watch" exited with 1.
```

**Comment by samthor** [comment]
Try `npm ci` to ensure your deps are up to date. There was a problem with the types ingestion which I fixed by revving the parser.

**Review by dotproto — APPROVED** [review]
I think I must have made a mistake when branching last time. Today I pulled the branch despite no new commits and my branch fast-forwarded, so I re-ran `npm ci`and everything worked as expected.

I took the liberty of diffing the generated "reference" directories before and after this PR and the only type that seems to have been changed by this PR is the one identified in the original bug report (#1421): the `ports` property of [events.UrlFilter](https://developer.chrome.com/docs/extensions/reference/events/#type-UrlFilter).

**Comment by samthor** [comment]
Thanks!

**Pull request merged**
