### PR TITLE
Styling `<code>`

### PR DESCRIPTION
**Pull request by chybie**
Example: Refer to `/blog/migrating-to-typescript/#making-any-call` for the updated styles.

### CODE REVIEW

**Review by TimvdLippe — APPROVED** [review]
Styling looks good!

**Review by robdodson — APPROVED** [review]

**Comment by TimvdLippe** [comment]
When will this PR be released? It seems like the styling on https://developer.chrome.com/blog/migrating-to-typescript/ is still using the old styles.

**Comment by chybie** [comment]
Oh, it's merged. @robdodson @samthor , did a quick check:
- It's also not caching issue. 
- It works in dev but after production build, the styles were purged somehow, it's not included in the .html file. 

Any ideas of where might this goes wrong before I take a closer look into this?

**Comment by robdodson** [comment]
It's possible that the clever style that we're using is not being properly detected by purgeCss's regex
https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_transforms/purify-css.js#L61

so it gets purged when we do a production build.

We may need to try rewriting the CSS so it's just:

```scss
code {
  ...
}

pre > code {
  // undo the background color and border radius on code
}
```

**Comment by chybie** [comment]
Created a new PR #633

**Comment by robdodson** [comment]
that seems to have fixed it. Thank you @chybie !

**Pull request merged**
