### PR TITLE
Change default value for selfBrowserSurface

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This change will make it compliant with Chrome behavior.

@eladalon1983 FYI

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
With https://chromium-review.googlesource.com/c/chromium/src/+/4008501 now merged, @eladalon1983 do you want to wait for Chrome 108 to reach stable channel or do you want to land this PR now?

**Comment by eladalon1983** [comment]
The question is trickier than it might initially appear, because it's a gradual rollout. That means that different developers will be exposed to the change at different times, and it might also get reverted at some moment. Wdyt, given that additional information?

**Comment by beaufortfrancois** [comment]
I'd rather wait for the gradual rollout to reach 100% before making this change then.

**Comment by beaufortfrancois** [comment]
@eladalon1983 What's the status?

**Comment by eladalon1983** [comment]
https://critique.corp.google.com/cl/490713846

**Review by eladalon1983 — COMMENTED** [review]
At the moment, this is at 50%, which means 'include' and 'exclude' are equally correct, and soon this will be at 100%. So merging right away makes sense to me. LGTM.

**Comment by beaufortfrancois** [comment]
@rachelandrew PTAL

**Review by rachelandrew — APPROVED** [review]

**Comment by Malikjavedibrahim** [comment]
Where am I and what is written, I don't understand, so please help

**Pull request merged**
