### PR TITLE
[OPFS article] Migrate article to web.dev

### PR DESCRIPTION
**Pull request by tomayac**
Fixes https://github.com/GoogleChrome/developer.chrome.com/issues/6459.

Changes proposed in this pull request:

- Add celebration aside.

### CODE REVIEW

**Comment by tomayac** [comment]
Once this is merged, I will create a separate PR to migrate the article to web.dev.

**Comment by rachelandrew** [comment]
@tomayac we don't have that aside here, which is why the build is broken.

Add it when you move the article, there's no need to add it first here as we don't have that tag on this site.

**Comment by tomayac** [comment]
Ooops. I made the edit just before cooking lunch and didn’t realize the aside isn’t there. Will fix this after lunch.

**Review by rachelandrew — APPROVED** [review]
To merge once the one on web.dev is merged.

**Pull request merged**
