### PR TITLE
[devtools-translate] Spanish - What's New in DevTools (Chrome 103)

### PR DESCRIPTION
**Pull request by midudev**
Spanish translation Chrome 101.

Closes https://github.com/GoogleChrome/developer.chrome.com/issues/3013.

### CODE REVIEW

**Comment by jecfish** [comment]
Thanks @midudev! Over to @Caballerog @and-oli for review!

**Review by Caballerog — COMMENTED** [review]
LGTM! Thanks for your time :-)

**Review by and-oli — APPROVED** [review]
LGTM. Many thanks for the translation!

**Comment by jecfish** [comment]
Gracias!

**Pull request merged**
