### PR TITLE
ContentMigrationBatch#SH5R86

### PR DESCRIPTION
**Pull request by simgobb**
https://www.html5rocks.com/en/tutorials/developertools/async-call-stack/
https://www.html5rocks.com/en/tutorials/developertools/auditpanel/
https://www.html5rocks.com/en/tutorials/developertools/chrome-33/
https://www.html5rocks.com/en/tutorials/developertools/chrome-35/
https://www.html5rocks.com/en/tutorials/developertools/devtools-terminal/

@rachelandrew

### CODE REVIEW

**Review by rachelandrew — CHANGES_REQUESTED** [review]
I had trouble getting this to build. Can you remove the package-lock from your commit and then merge in the up to date main branch. There have been some changes to the underlying code for this repo and I wonder if that's the issue.

**Comment by simgobb** [comment]
@rachelandrew I've removed the PackageLock.json file and did a merge with an up to date main. Let me know if this solves the issue, otherwise I can just start from a fresh branch. I've got backup files, so it wouldn't take me long to set that up either.

**Comment by rachelandrew** [comment]
@simgobb 

>  I've got backup files, so it wouldn't take me long to set that up either.

That might be a good idea, we seem to be in some sort of mess, and I'm not sure how to fix it.

**Comment by simgobb** [comment]
@rachelandrew No worries. I'll start from a completely clean clone and get it from there. I'll close this PR now and send over the new PR this morning

**Pull request closed without merging**
