### PR TITLE
Archive README

### PR DESCRIPTION
**Pull request by alexandrascript**
Announce archive in README

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]

**Comment by paulirish** [comment]
Do you want to mark the repo as archived? I could do that if we're ready.

**Comment by rachelandrew** [comment]
@paulirish we can do, I still have some issues to move over to the new issuetracker, but presumably it's all still available read-only once archived.

**Comment by paulirish** [comment]
yeah the whole repo/issues will remain read only. 
but if there's any places you still wanna leave a comment, we should do that first.

i'm not in a rush, just offering to help. :)

**Comment by rachelandrew** [comment]
thanks :) I'll have a look through as if there are any public issues to move, I'd like to comment and let them know where it went. Then we should be good to go.

**Pull request merged**
