### PR TITLE
Code Error Fixed [ Improving Article ]

### PR DESCRIPTION
**Pull request by CrazyCodeLearner**

### CODE REVIEW

**Comment by samthor** [comment]
I'm actually not sure if this is valid, that this is now required. @awfuchs ?

**Comment by samthor** [comment]
Thanks, but please sign the CLA.

**Comment by heyawhite** [comment]
@CrazyCodeLearner just checking in -- to publish in a Google open source repo, please sign the CLA. Refer to the earlier comment from google-cla with more details.

**Comment by rachelandrew** [comment]
Closing as contributor was asked to sign the CLA but has not responded.

**Comment by CrazyCodeLearner** [comment]
Why should i sign for CLA

**Comment by jpmedley** [comment]
Because our Lawyers won't let us accept anything from you if you don't.

**Pull request closed without merging**
