### PR TITLE
Update ascent value for Poppins to 1050

### PR DESCRIPTION
**Pull request by wixzi**
Changes proposed in this pull request:

- Update ascent value for Poppins to 1050

### CODE REVIEW

**Comment by wixzi** [comment]
@devnook can you have a look?

**Comment by wixzi** [comment]
@rachelandrew  can you have a look?

**Comment by rachelandrew** [comment]
@wixzi I don't know what the rationale for this change is. If proposing a change please explain why (and provide links to back up your suggestion).

**Comment by wixzi** [comment]
> @wixzi I don't know what the rationale for this change is. If proposing a change please explain why (and provide links to back up your suggestion).

Screenshot 2023-07-14 at 12 44 00

Fix that error in the article 
https://developer.chrome.com/blog/font-fallbacks/#:~:text=There%20are%20two%20possible%20approaches,overrides%20API%20and%20size%2Dadjust%20.

**Comment by wixzi** [comment]
@khempenius Please have a look. :)

**Comment by rachelandrew** [comment]
If the value is wrong, please provide a reference, thanks!

**Review by khempenius — APPROVED** [review]

**Comment by wixzi** [comment]
> If the value is wrong, please provide a reference, thanks!

Screenshot 2023-07-14 at 12 44 00

**Review by rachelandrew — APPROVED** [review]

**Pull request merged**
