### PR TITLE
Add doc for Lighthouse bfcache audit

### PR DESCRIPTION
**Pull request by adamraine**
Adds documentation for the new Lighthouse back/forward cache audit

https://github.com/GoogleChrome/lighthouse/pull/14465

Drafting doc: 🔒 [go/bf-cache-audit-docs](http://goto.google.com/bf-cache-audit-docs)

### CODE REVIEW

**Review by malchata — APPROVED** [review]
LGTM!

Does this need to be redirected to from web.dev, or is this an entirely new audit?

**Comment by adamraine** [comment]
> Does this need to be redirected to from web.dev, or is this an entirely new audit?

It's an entirely new audit.

**Comment by malchata** [comment]
SGTM! Merge when you're ready!

**Comment by adamraine** [comment]
I don't have permission to merge, are you able to do it?

**Comment by malchata** [comment]
It looks like the `Check / stage` workflow is failing. I'm a bit hesitant to merge this if it's an important job that could break the site on deploy.

@devnook, are you aware of whether the workflow job mentioned above is crucial to merging? Does it fail often, or is this unusual?/

**Pull request merged**
