### PR TITLE
Updated Privacy Sandbox events page

### PR DESCRIPTION
**Pull request by samdutton**
@kevinkiklee FYI

### CODE REVIEW

**Comment by samdutton** [comment]
Also created bug for migration.

**Review by nancymic2 — APPROVED** [review]

**Review by kevinkiklee — CHANGES_REQUESTED** [review]
DO NOT MERGE

**Review by kevinkiklee — APPROVED** [review]
The videos have been edited and now can be published

**Comment by liakot098** [comment]
What's up man how is it???

**Pull request merged**
