### PR TITLE
[JA] Translations

### PR DESCRIPTION
**Pull request by ilyaspiridonov**
Translates 3 articles into Japanese: 
[blog/expanding-privacy-sandbox-testing-2023](https://gitlocalize.com/repo/7832/ja/review/54459)
[blog/first-party-sets-sameparty](https://gitlocalize.com/repo/7832/ja/review/54774)
[blog/rename-trust-tokens](https://gitlocalize.com/repo/7832/ja/review/54933)

@agektmr

### CODE REVIEW

**Review by agektmr — APPROVED** [review]
LGTM

**Comment by agektmr** [comment]
@ilyaspiridonov github says this branch is out-of-date. Could you rebase?

**Comment by ilyaspiridonov** [comment]
@agektmr should be good now

**Comment by agektmr** [comment]
@anusmitaray @mihajlija @heyawhite could one of you please approve this PR?

**Pull request merged**
