### PR TITLE
[devtools-translate] Portuguese - What's New in DevTools (Chrome 103) #3016

### LINKED ISSUE #3016: [devtools-translate] Portuguese - What's New in DevTools (Chrome 103)
Post: https://developer.chrome.com/blog/new-in-devtools-103/
Translated by: June 19

Translator: @alvarocamillont
Reviewers: @khaosdoctor

### PR DESCRIPTION
**Pull request by alvarocamillont**
Fixes #3016

Changes proposed in this pull request:

Add portuguese translations for What's New in DevTools M103

### CODE REVIEW

**Comment by jecfish** [comment]
Thanks Alvaro! Over to @khaosdoctor and @andreban for review.

**Review by khaosdoctor — COMMENTED** [review]
LGTM

**Review by andreban — APPROVED** [review]
Sorry for the delay here. LGTM, thank you!

**Review by jecfish — APPROVED** [review]

**Comment by jecfish** [comment]
Thank you all!

**Pull request merged**
