### PR TITLE
[devtools-engineering] Added an article about top layer DevTools support

### PR DESCRIPTION
**Pull request by AlinaVarkki**
Fixes: #3194 
Added an article about the support of top layer elements in DevTools.

### CODE REVIEW

**Comment by rachelandrew** [comment]
@AlinaVarkki as mentioned in the other thread, this needs editing. Are you already working with one of the tech writers on this? If so can you let me know who reviewed it?

Otherwise, please initially [raise an issue](https://github.com/GoogleChrome/developer.chrome.com/issues/new?assignees=rachelandrew&labels=new+content&template=propose-new-content.md&title=content%3A+TODO) with your content proposal and a link to your draft in Google docs.

This [handbook entry](https://web.dev/handbook/quick-start/) details our process (it's on web.dev but the instructions are similar for both sites).

**Review by rachelandrew — APPROVED** [review]

**Comment by sofiayem** [comment]
Not merging yet. Waiting for @hanselfmu to update screenshots.

**Comment by hanselfmu** [comment]
The screenshots and the content have been updated. PTAL again and it's good to go from my side. Thanks!

**Comment by Rana9t** [comment]
> Fixes: #3194 Added an article about the support of top layer elements in DevTools.

**Pull request merged**
