### PR TITLE
Add page for manfest key: short_name

### PR DESCRIPTION
**Pull request by IanStanion-google**
Implemented content for manifest key short_name

### CODE REVIEW

**Comment by IanStanion-google** [comment]
I still have the tab for this open even though I'm not assigned anymore. Is there anything I can do to help close this issue?
@dotproto @jpmedley

**Review by dotproto — CHANGES_REQUESTED** [review]

**Comment by jpmedley** [comment]
@dotproto If you're done, can you please formally LGTM this?

**Comment by oliverdunk** [comment]
It looks like this actually exists already as a subsection of the name documentation: https://developer.chrome.com/docs/extensions/mv3/manifest/name/#short_name

Does it make sense to have both or is there a risk of duplication?

I'll hold off reviewing for now.

**Comment by jpmedley** [comment]
>It looks like this actually exists already as a subsection of the name documentation: https://developer.chrome.com/docs/extensions/mv3/manifest/name/#short_name

Good catch. Duplicate content is a documentation anti-pattern. Here's what we should do:

1. Finish this PR as is.
2. Create a new PR to deduplicate the content and add a line to both such as 'See also, _other_key_.'

**Comment by oliverdunk** [comment]
> > It looks like this actually exists already as a subsection of the name documentation: https://developer.chrome.com/docs/extensions/mv3/manifest/name/#short_name
> 
> Good catch. Duplicate content is a documentation anti-pattern. Here's what we should do:
> 
> 1. Finish this PR as is.
> 2. Create a new PR to deduplicate the content and add a line to both such as 'See also, _other_key_.'

I've opened https://github.com/GoogleChrome/developer.chrome.com/issues/4882 for this. Happy with the rest of the content so approving and re-assigning to you for writing review :)

**Review by oliverdunk — APPROVED** [review]
Happy from the technical POV.

**Review by ali-spivak — APPROVED** [review]

**Review by ali-spivak — APPROVED** [review]

**Review by jpmedley — APPROVED** [review]

**Comment by jpmedley** [comment]
@IanStanion-google You may now merge this.

**Pull request merged**
