### PR TITLE
Add autopip blog post

### PR DESCRIPTION
**Pull request by beaufortfrancois**
@rachelandrew Please review

**Warning**: Update publication date

Live preview: https://pr-7683-static-dot-dcc-staging.uc.r.appspot.com/blog/automatic-picture-in-picture/

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]

**Comment by rachelandrew** [comment]
@beaufortfrancois will you be merging this so I can link it from the beta post?

**Comment by beaufortfrancois** [comment]
I'll be publishing this article November 28th as agreed with the Chrome Media UX team.

**Comment by rachelandrew** [comment]
@beaufortfrancois we'll be in content freeze then for the migration. So you'll need to publish before the 20th November, or wait until we're on DevSite on the 5th December.

**Comment by beaufortfrancois** [comment]
After discussing the team, I'll publish this post November 17th.

**Pull request merged**
