### PR TITLE
Rework background/service worker content

### PR DESCRIPTION
**Pull request by awfuchs**
Remove page for "Migrate to event-driven background scripts" because its content is replicated in "Migrating from background pages to service workers". Redirect the removed page to that.

Reword content in "Manage events with background scripts" to refer to service workers.

### CODE REVIEW

**Comment by dotproto** [comment]
A thought just crossed my mind. @awfuchs, what do you think about removing `/docs/extensions/mv2/migrating_to_service_workers/` and redirecting to `docs/extensions/mv3/migrating_to_service_workers/`?

**Comment by awfuchs** [comment]
> A thought just crossed my mind. @awfuchs, what do you think about removing `/docs/extensions/mv2/migrating_to_service_workers/` and redirecting to `/docs/extensions/mv3/migrating_to_service_workers/`?

Good call -- Done!

**Comment by dotproto** [comment]
Just commited some changes to this branch.

1. Updates code samples to use [Standard formatting](https://standardjs.com/).
2. Updates code samples to use MV3 APIs
3. Adds links to relevant API docs.
4. Reformat some paragraphs to wrap at 100 characters.

Some of the links mentioned in #3 may be repetitive. I figured it was better to err on the side of making it easy to find the relevant docs. The main use case I had in mind was a user opening a deep link to a specific sub-heading.

**Review by dotproto — APPROVED** [review]
LGTM

**Comment by dotproto** [comment]
@awfuchs, we discussed overlap between `migrating_to_service_workers`, `background_migration`, and `background_pages` and the possibility of merging all 3 docs. This PR doesn't touch the `background_pages` doc; did you have any additional thoughts on the relationship between that page and `migrating_to_service_workers`?

**Comment by awfuchs** [comment]
> @awfuchs, we discussed overlap between `migrating_to_service_workers`, `background_migration`, and `background_pages` and the possibility of merging all 3 docs. This PR doesn't touch the `background_pages` doc; did you have any additional thoughts on the relationship between that page and `migrating_to_service_workers`?

In fact that is one of the files in this PR. I have changed the wording (but not the filename) throughout the file, but it does have some missing code at line 54, to import additional script files into the service worker.

The plan is to drop the "migrate to event-driven", because all its content is duplicated elsewhere, and to merge the remaining two. In this PR I'm going for the lower-hanging fruit, making things MV3-valid. When that's ironed out then I still plan to merge them.

**Review by dotproto — APPROVED** [review]

**Review by robdodson — APPROVED** [review]

**Pull request merged**
