### PR TITLE
[2023-06-12] Add blog post on Chrome for Testing

### PR DESCRIPTION
**Pull request by mathiasbynens**
Please publish this on 2023-06-12, i.e. next Monday. Thanks!

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]

**Comment by christian-bromann** [comment]
@mathiasbynens I am planning making a change to WebdriverIO allowing users to now define a `browserVersion` capability and getting the desired "Chrome for Testing" browser. Would you be open to add a comment mentioning it?

**Comment by mathiasbynens** [comment]
> @mathiasbynens I am planning making a change to WebdriverIO allowing users to now define a `browserVersion` capability and getting the desired "Chrome for Testing" browser. Would you be open to add a comment mentioning it?

That sounds great — do you have a link with more details?

For the purposes of this announcement I think we’ll stick to the basics for now, but I could see an “Ecosystem integrations” overview in a future edit or as a separate blog post.

**Comment by christian-bromann** [comment]
Sounds good, let me know if I can contribute to this.

**Comment by rachelandrew** [comment]
@mathiasbynens I've just merged this so it should be on the site within the next hour.

**Comment by mathiasbynens** [comment]
Thanks @rachelandrew!

**Pull request merged**
