### PR TITLE
fix: typo in browserAction doc

### LINKED ISSUE #603: An invalid link in documentation of browserAction API.
**Describe the bug**
An Invalid link in documentation of browserAction API

**To Reproduce**
1. Go to ''https://developer.chrome.com/docs/extensions/reference/browserAction/"
2. Click on [popup link](https://developer.chrome.com/docs/extensions/reference/browserAction/#popups) in description
3. It doesn't take to popup section of documentation.

**Expected behavior**
It should take to popup section of the documentation
 
**Additional context**
There is a typo in the markdown file.

### PR DESCRIPTION
**Pull request by Simply-divine**
Fixes #603 

Changes proposed in this pull request:

- fixed a typo

### CODE REVIEW

**Comment by jpmedley** [comment]
@Simply-divine Thanks for submitting the typo fix. Can you please sign the CLA.

**Comment by jpmedley** [comment]
@Simply-divine Do you have multiple emails associated with your GitHub account?

@robdodson How did you fix this with Rachel?

**Comment by robdodson** [comment]
@jpmedley it looks like the CLA check is passing
image

I'm not sure why it's not setting the cla: yes label.

**Comment by Simply-divine** [comment]
@jpmedley yes I do have multiple emails linked with github account but I have signed CLA using primary email of my github account.

**Pull request merged**
