### PR TITLE
Remove references to the "spellcheck" manifest key.

### PR DESCRIPTION
**Pull request by karan173**
This is being removed from the chromium repo in https://chromium-review.googlesource.com/c/chromium/src/+/2621972.

### CODE REVIEW

**Comment by dotproto** [comment]
@kaycebasques, as I recall you formatted the preformatted manifest file on this page. Are there any considerations to keep in mind when updating the contents of this pre block?

**Review by dotproto — APPROVED** [review]
LGTM barring any notes from @kaycebasques.

**Comment by kaycebasques** [comment]
@awfuchs please confirm that the new page looks correct (by running the branch locally and checking the rendered page)

**Review by awfuchs — APPROVED** [review]

**Comment by karan173** [comment]
Hmm I am not used to github based workflows!! Not sure what happened here but some combination of local merge/rebase let to this PR having all these different commits. I'll just go ahead and close this PR and open a new one.

**Pull request closed without merging**
